module.exports = {
    fields: {
        id_vehicule: { type: 'int' },
        year: { type: 'int' },
        month: { type: 'int' },
        day: { type: 'int' },
        tracking_time: { type: 'timestamp'},
        acc_status: { type: 'tinyint' },
        accelerator_pedal_position: { type: 'decimal' },
        actual_profile: {type: 'int'},
        alert_checked: {type:'tinyint'},
        altitude: { type: 'int' },
        alv_data: { type: 'text' },
        angle:{ type: 'int' },
        area_code: { type: 'int' },
        can_fuel_level: { type: 'decimal' },
        can_speed: { type: 'decimal' },
        cell_id: { type: 'int' },
        crash_detect: { type: 'decimal' },
        current_battery: { type: 'double' },
        distence_corrected: {type: 'tinyint'},
        door_status: { type: 'decimal' },
        ecodrive_duration: { type: 'decimal' },
        ecodrive_type: { type: 'decimal' },
        ecodrive_value: { type: 'decimal' },
        engine_oil_level: { type: 'decimal' },
        engine_rpm: { type: 'decimal' },
        engine_temp: { type: 'decimal' },
        engine_worktime: { type: 'decimal' },
        etat: { type: 'int' },
        etatsignal: { type: 'int' },
        event:{ type: 'int' },
        external_power: { type: 'double' },
        fuel_consumed: { type: 'decimal' },
        fuel_rate: { type: 'decimal' },
        gnss_status: { type: 'int' },
        gps_hdop: { type: 'double' },
        gps_pdop: { type: 'double' },
        gps_speed: { type: 'int' },
        id_device: { type: 'int' },
        id_tracking: {type: 'bigint'},
        input: { type: 'text' },
        internal_battery: { type: 'double' },
        jaming:{ type: 'decimal' },
        km: { type: 'double' },
        latitude: { type: 'double' },
        longitude: { type: 'double' },
        message: { type: 'text' },
        movement: { type: 'tinyint' },
        operator_code: { type: 'int' },
        panic_button_status: { type: 'tinyint' },
        pcb_temp: { type: 'double' },
        priority: { type: 'int' },
        reception_timespan :{ type: 'timestamp'},
        reservoir1: { type: 'double' },
        reservoir2: { type: 'double' },
        rfid: { type: 'text' },
        satellites: { type: 'int' },
        sleep_mode: { type: 'int' },
        speed: { type: 'double' },
        temperature1: { type: 'double' },
        temperature2: { type: 'double' },
        total_mileage: { type: 'decimal' },
        tracking_on_event: { type: 'tinyint' },
    },
    key : [['id_vehicule','year','month'],'tracking_time'],
    clustering_order: {tracking_time: 'desc'},
}

/**/